CREATE SEQUENCE DB_ID_SEQ
  START WITH 2
  INCREMENT BY 1;

CREATE TABLE WEATHER_DATA (
    ID BIGINT NOT NULL PRIMARY KEY,
    POST_CODE VARCHAR NOT NULL,
    DATE DATE NOT NULL,
    MIN_TEMP NUMBER NOT NULL,
    AVG_TEMP NUMBER NOT NULL,
    MAX_TEMP NUMBER NOT NULL,
    ALL_RAINFALL NUMBER NOT NULL,
    DAILY_MAX_RAINFALL NUMBER NOT NULL
);